# Generated by Django 3.0.1 on 2020-01-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cme_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cme_pid', models.CharField(blank=True, max_length=10, null=True)),
                ('point_price', models.FloatField(null=True)),
                ('exchange', models.CharField(blank=True, max_length=255, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'symbol',
                'verbose_name_plural': 'symbols',
                'db_table': 'symbols',
            },
        ),
    ]
