# Generated by Django 3.0.1 on 2020-01-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(blank=True, max_length=255, null=True)),
                ('option_code', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration', models.DateField(null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapi.Symbol')),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='ComfortZones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('call_settle', models.FloatField(null=True)),
                ('put_settle', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fxapi.Option')),
            ],
            options={
                'verbose_name': 'comfort_zone',
                'verbose_name_plural': 'comfort_zones',
                'db_table': 'comfort_zones',
            },
        ),
    ]
