# Generated by Django 3.0.1 on 2020-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0002_comfortzones_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='fx_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
