# Generated by Django 3.0.1 on 2020-01-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0003_symbol_fx_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='cab',
            field=models.FloatField(null=True),
        ),
    ]
