# Generated by Django 3.0.1 on 2020-01-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0004_symbol_cab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comfortzones',
            old_name='call_settle',
            new_name='call_strike',
        ),
        migrations.RenameField(
            model_name='comfortzones',
            old_name='put_settle',
            new_name='put_strike',
        ),
    ]
