# Generated by Django 3.0.1 on 2020-01-29 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0005_auto_20200129_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfortzones',
            name='option',
        ),
        migrations.AddField(
            model_name='comfortzones',
            name='option_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comfortzones',
            name='symbol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fxapi.Symbol'),
            preserve_default=False,
        ),
    ]
