# Generated by Django 3.0.1 on 2020-01-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0006_auto_20200129_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comfortzones',
            name='symbol',
        ),
    ]
