# Generated by Django 3.0.1 on 2020-01-29 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0007_remove_comfortzones_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfortzones',
            name='symbol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fxapi.Symbol'),
        ),
    ]
