# Generated by Django 3.0.1 on 2020-01-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0008_comfortzones_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='comfortzones',
            name='fx_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
