# Generated by Django 3.0.1 on 2020-03-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0009_comfortzones_fx_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortZonesCreateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'comfort_zone_create_result',
                'verbose_name_plural': 'comfort_zone_create_results',
                'db_table': 'comfort_zone_create_results',
            },
        ),
    ]
