# Generated by Django 3.0.1 on 2020-04-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fxapi', '0010_comfortzonescreateresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComfortZonesCreateResult',
        ),
    ]
